version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      # Load environment variables from a file
      # Developers need to create a .env file in the frontend root
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev", "--verbose", "--", "--host"]
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      # Load environment variables from a file
      # Developers need to create a .env file in the frontend root
      - FLASK_ENV=${FLASK_ENV:-development}
    volumes:
      - ./backend:/app
      - data:/app/data
    command: ["python", "-m", "flask", "--app", "src/app", "run", "--host=0.0.0.0", "--port=5000"]
    depends_on:
      - metadata_updater


  metadata_updater:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - data:/app/data
    command: ["python", "src/update_metadata.py"]

volumes:
  data:
    driver: local
  node_modules:
    driver: local
