name: get_file_and_subject_metadata

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          git config --global user.email "admin@gutsproject.org"
          git config --global user.name "Gutsproject Github Admin"
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Fetch metadata
        env:
          WEBDAV_USERNAME: ${{ secrets.webdav_username }}
          WEBDAV_PASSWORD: ${{ secrets.webdav_password }}
        run: |
          echo "Downloading subject-level metadata"
          curl -u "$WEBDAV_USERNAME":"$WEBDAV_PASSWORD" -o data/guts-subject-level-metadata.json https://erasmus-data.irods.surfsara.nl/research-guts-dummy/metadata/guts-subject-level-metadata.json
          echo "Downloading file-level metadata"
          curl -u "$WEBDAV_USERNAME":"$WEBDAV_PASSWORD" -o data/guts-file-level-metadata.json https://erasmus-data.irods.surfsara.nl/research-guts-dummy/metadata/guts-file-level-metadata.json
          echo "Downloading measure-level metadata"
          curl -u "$WEBDAV_USERNAME":"$WEBDAV_PASSWORD" -o data/guts-measure-overview.json https://erasmus-data.irods.surfsara.nl/research-guts-dummy/metadata/guts-measure-overview.json
      - name: Commit if modified
        run: |
          if [[ `git status --porcelain` ]]; then
            # Changes
            git add --all
            git commit -m "Update file-, subject-, and measure- level metadata from YODA"
            git push origin main
          else
            # No changes
            echo "No edits were made to metadata; therefore no changes were committed"
          fi